# name: Generate GitHub Metrics

# on:
#   schedule:
#     - cron: "0 0 * * *" # Runs daily
#   workflow_dispatch: # Allows manual execution

# jobs:
#   metrics:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Generate metrics
#         uses: lowlighter/metrics@latest
#         with:
#           filename: metrics.plugin.isocalendar.svg
#           token: ${{ secrets.METRICS_TOKEN }}
#           base: ""
#           plugin_isocalendar: yes
#           plugin_isocalendar_duration: full-year
#       - name: Labels
#         uses: lowlighter/metrics@latest
#         with:
#           filename: metrics.plugin.topics.svg
#           token: NOT_NEEDED
#           base: ""
#           plugin_topics: yes
#           plugin_topics_limit: 12
#       - name: Full-year calendar
#         uses: lowlighter/metrics@latest
#         with:
#           filename: metrics.plugin.isocalendar.fullyear.svg
#           token: ${{ secrets.METRICS_TOKEN }}
#           base: ""
#           plugin_isocalendar: yes
#           plugin_isocalendar_duration: full-year
#       - name: Icons
#         uses: lowlighter/metrics@latest
#         with:
#           filename: metrics.plugin.topics.icons.svg
#           token: NOT_NEEDED
#           base: ""
#           plugin_topics: yes
#           plugin_topics_limit: 0
#           plugin_topics_mode: icons